Authorize OIDC
kanoonthteam/directus pull request #2
Opened 2021-08-15 17:10 UTC by mildiemilk

2021-08-16 14:49 UTC, aunsuwijak requested changes
I don't think we need `package-lock.json` file na. The project is managed with `lerna` already.

2021-08-16 14:49 UTC, aunsuwijak commented on .npmrc
> +engine-strict=false
This one doesn't require in the commit right now since I think `oidc-provider` team (panva) will fix it soon.

2021-08-16 14:49 UTC, aunsuwijak commented on api/package.json
> -		"oidc-provider": "^7.5.4",
Please revert this one.

2021-08-16 14:49 UTC, aunsuwijak commented on api/src/controllers/oidc.ts
> +				const { accountId, userId } = await authenticationService.authorize({
Do we still use `accountId`?

2021-08-16 14:49 UTC, aunsuwijak commented on api/src/oidc.ts
> +		await database('directus_users').update({ token: token.jti }).whereRaw('LOWER(??) = ?', ['email', token.accountId]);
- I might surround this with `try { ... } catch`, but this could be later. BTW, can you give more explanation about the hooks (`extraTokenClaims`), `token.jti` and `token.accountId` in a comment.
- I'm not sure why do you need `whereRaw`, an `accountId` can have `.toLowerCase()` right?

2021-08-16 14:49 UTC, aunsuwijak commented on api/src/services/authentication.ts
> +			accountId: email,
I think it would be better to rename `accountId` to `email` for better understanding.

2021-08-16 18:04 UTC, mildiemilk commented on api/src/controllers/oidc.ts
> +				const { accountId, userId } = await authenticationService.authorize({
yes, `oidc.interactionResult` required this field

2021-08-16 18:06 UTC, mildiemilk commented on api/src/services/authentication.ts
> +			accountId: email,
okay, but `oidc.interactionResult`  required `accountId` as a `email`

2021-08-16 18:15 UTC, mildiemilk commented on api/src/controllers/oidc.ts
> +						accountId: email,
`oidc.interactionResult` required accountId as a email

2021-08-16 18:18 UTC, mildiemilk commented on api/src/oidc.ts
> +		await database('directus_users').update({ token: token.jti }).whereRaw('LOWER(??) = ?', ['email', token.accountId]);
I still keep `whereRaw` logic the same as the owner

2021-08-20 14:38 UTC, aunsuwijak requested changes

2021-08-20 14:38 UTC, aunsuwijak commented on api/src/app.ts
> +	app.get('/admin', (req, res) => res.send(html));
What is the diff between L177 and L179?

2021-08-20 14:38 UTC, aunsuwijak commented on api/src/controllers/auth.ts
> +		const redirect = req.session.redirect || '/admin/collections';
`'admin/collections'` shouldn't be hard coded.

2021-08-20 14:38 UTC, aunsuwijak commented on api/src/controllers/oidc.ts
> +				const newGrantId = await grant.save();
Does this change has any meaning?

2021-08-20 14:38 UTC, aunsuwijak commented on api/src/grant.ts
> +// const enabledProviders = toArray(env.OAUTH_PROVIDERS).map((provider) => provider.toLowerCase());
Please remove if it is unused.

2021-08-21 13:05 UTC, aunsuwijak approved these changes

2021-08-21 13:06 UTC, merged